FROM python:3.7-slim 
WORKDIR /app
COPY requirements.txt /app/ 
COPY ./examples /app/examples/
RUN pip install --trusted-host pypi.python.org -r requirements.txt 
RUN mkdir -p /usr/share/man/man1 && apt-get update && apt-get install -y build-essential wget software-properties-common tmux vim openjdk-11-jdk-headless
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - && apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-6.0 main" && apt-get update && apt-get install -y clang-6.0 llvm 