FROM python:3.7-slim 
WORKDIR /app
COPY requirements.txt /app/ 
COPY ./examples /app/examples/
RUN pip install --trusted-host pypi.python.org -r requirements.txt 
RUN mkdir -p /usr/share/man/man1 && apt-get update && apt-get install -y build-essential wget software-properties-common openjdk-11-jdk-headless
RUN wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add - 
RUN apt-get update

# Get KLEE dependencies (LLVM 6.0) [http://klee.github.io/build-llvm60/]
RUN apt-get install -y curl libcap-dev git unzip doxygen libsqlite3-dev libgoogle-perftools-dev libtcmalloc-minimal4 cmake 
RUN pip install tabulate
RUN apt-get install -y clang-6.0 llvm-6.0 llvm-6.0-dev llvm-6.0-tools zsh 

# Install z3 
RUN git clone https://github.com/Z3Prover/z3/ 
RUN cd /app/z3 && python scripts/mk_make.py 
RUN cd /app/z3/build && make && make install
RUN pip install z3-solver

# Get KLEE 
RUN git clone https://github.com/klee/klee.git
RUN mkdir /app/build
RUN cd build && cmake <CMAKE_OPTIONS> <iKLEE_SRC_DIRECTORY>


## === Finish Configuring and Testing Everything Below Here === 

# AFL (Dependency for Kelinci) 
RUN git clone https://github.com/google/AFL

# Kelinci: https://github.com/isstac/kelinci
RUN git clone https://github.com/isstac/kelinci

# JQF + Zest 
RUN git clone https://github.com/rohanpadhye/jqf

# JPF (Symbolic Java Path Finder): https://github.com/SymbolicPathFinder/jpf-symbc 
# Refer to https://github.com/SymbolicPathFinder/jpf-symbc/wiki/Documentation 
RUN git clone https://github.com/javapathfinder/jpf-core
RUN git clone https://github.com/SymbolicPathFinder/jpf-symbc
RUN mkdir jpf && mv jpf-core jpf && mv jpf-symbc jpf 
COPY site.properties /app/jpf/

# PRISM: https://www.prismmodelchecker.org/manual/InstallingPRISM/Instructions#binaries 
COPY /dependencies/prism-4.5-linux64.tar.gz /app/
RUN gunzip prism-4.5-linux64.tar.gz && tar xf prism-4.5-linux64.tar && cd prism-4.5-linux64 && ./install.sh
RUN rm -rf /app/prism-4.5-linux64.tar && rm /app/requirements.txt 
