# all: 

01_greatestof3: 01_greatestof3_main.c 01_greatestof3.c
	clang -pedantic -Wall -Wextra 01_greatestof3_main.c -o 01_greatestof3

02_fib: 02_fib_main.c 02_fib.c
	clang -pedantic -Wall -Wextra 02_fib_main.c -o 02_fib

03_sign: 03_sign_main.c 03_sign.c
	clang -pedantic -Wall -Wextra 03_sign_main.c -o 03_sign

04_prime: 04_prime_main.c 04_prime.c
	clang -pedantic -Wall -Wextra 04_prime_main.c -o 04_prime

05_parity: 05_parity_main.c 05_parity.c
	clang -pedantic -Wall -Wextra 05_parity_main.c -o 05_parity

06_parindrome: 06_parindrome_main.c 06_parindrome.c
	clang -pedantic -Wall -Wextra 06_parindrome_main.c -o 06_parindrome

10_find_val_in_array: 10_find_val_in_array_main.c 10_find_val_in_array.c
	clang -pedantic -Wall -Wextra 10_find_val_in_array_main.c -o 10_find_val_in_array

11_array_max: 11_array_max_main.c 11_array_max.c
	clang -pedantic -Wall -Wextra 11_array_max_main.c -o 11_array_max

12_check_sorted_array: 12_check_sorted_array_main.c 12_check_sorted_array.c
	clang -pedantic -Wall -Wextra 12_check_sorted_array_main.c -o 12_check_sorted_array

13_check_arrays_equal: 13_check_arrays_equal_main.c 13_check_arrays_equal.c
	clang -pedantic -Wall -Wextra 13_check_arrays_equal_main.c -o 13_check_arrays_equal

14_lexicographic_array_compare: 14_lexicographic_array_compare_main.c 14_lexicographic_array_compare.c
	clang -pedantic -Wall -Wextra 14_lexicographic_array_compare_main.c -o 14_lexicographic_array_compare

15_check_heap_order: 15_check_heap_order_main.c 15_check_heap_order.c
	clang -pedantic -Wall -Wextra 15_check_heap_order_main.c -o 15_check_heap_order

16_binary_search: 16_binary_search_main.c 16_binary_search.c
	clang -pedantic -Wall -Wextra 16_binary_search_main.c -o 16_binary_search

17_edit_dist: 17_edit_dist_main.c 17_edit_dist.c
	clang -pedantic -Wall -Wextra 17_edit_dist_main.c -o 17_edit_dist

18_longest_common_subsequence: 18_longest_common_subsequence_main.c 18_longest_common_subsequence.c
	clang -pedantic -Wall -Wextra 18_longest_common_subsequence_main.c -o 18_longest_common_subsequence




# This is a "dummy" target.  When we tell Make to make clean, it has no
# dependencies and it will just run the command below, which removes all object
# files and the executable (if they exist).
clean:
	rm -rf *.o 