CXX = clang
CXX_FLAGS = -pedantic -Wall -Wextra

all: 01_greatestof3 02_fib 03_sign 04_prime 05_parity 06_palindrome 10_find_val_in_array 11_array_max 12_check_sorted_array 13_check_arrays_equal 14_lexicographic_array_compare 15_check_heap_order 16_binary_search 17_edit_dist 18_longest_common_subsequence 19_longest_common_increasing_subsequence 20_bubblesort 21_insertionsort 22_selectionsort 23_mergesort 24_quicksort 25_heapsort 26_quicksort 30_euclid_GCD 31_sieve_of_eratosthenes 32_newtons_method 50_check_sorted_or_reverse 51_variance 60_array_summary

01_greatestof3: 01_greatestof3_main.c 01_greatestof3.c
	$(CXX) $(CXX_FLAGS) 01_greatestof3_main.c -o 01_greatestof3

02_fib: 02_fib_main.c 02_fib.c
	$(CXX) $(CXX_FLAGS) 02_fib_main.c -o 02_fib

03_sign: 03_sign_main.c 03_sign.c
	$(CXX) $(CXX_FLAGS) 03_sign_main.c -o 03_sign

04_prime: 04_prime_main.c 04_prime.c
	$(CXX) $(CXX_FLAGS) 04_prime_main.c -o 04_prime

05_parity: 05_parity_main.c 05_parity.c
	$(CXX) $(CXX_FLAGS) 05_parity_main.c -o 05_parity

06_palindrome: 06_palindrome_main.c 06_palindrome.c
	$(CXX) $(CXX_FLAGS) 06_palindrome_main.c -o 06_palindrome

10_find_val_in_array: 10_find_val_in_array_main.c 10_find_val_in_array.c
	$(CXX) $(CXX_FLAGS) 10_find_val_in_array_main.c -o 10_find_val_in_array

11_array_max: 11_array_max_main.c 11_array_max.c
	$(CXX) $(CXX_FLAGS) 11_array_max_main.c -o 11_array_max

12_check_sorted_array: 12_check_sorted_array_main.c 12_check_sorted_array.c
	$(CXX) $(CXX_FLAGS) 12_check_sorted_array_main.c -o 12_check_sorted_array

13_check_arrays_equal: 13_check_arrays_equal_main.c 13_check_arrays_equal.c
	$(CXX) $(CXX_FLAGS) 13_check_arrays_equal_main.c -o 13_check_arrays_equal

14_lexicographic_array_compare: 14_lexicographic_array_compare_main.c 14_lexicographic_array_compare.c
	$(CXX) $(CXX_FLAGS) 14_lexicographic_array_compare_main.c -o 14_lexicographic_array_compare

15_check_heap_order: 15_check_heap_order_main.c 15_check_heap_order.c
	$(CXX) $(CXX_FLAGS) 15_check_heap_order_main.c -o 15_check_heap_order

16_binary_search: 16_binary_search_main.c 16_binary_search.c
	$(CXX) $(CXX_FLAGS) 16_binary_search_main.c -o 16_binary_search

17_edit_dist: 17_edit_dist_main.c 17_edit_dist.c
	$(CXX) $(CXX_FLAGS) 17_edit_dist_main.c -o 17_edit_dist

18_longest_common_subsequence: 18_longest_common_subsequence_main.c 18_longest_common_subsequence.c
	$(CXX) $(CXX_FLAGS) 18_longest_common_subsequence_main.c -o 18_longest_common_subsequence

19_longest_common_increasing_subsequence: 19_longest_common_increasing_subsequence_main.c 19_longest_common_increasing_subsequence.c
	$(CXX) $(CXX_FLAGS) 19_longest_common_increasing_subsequence_main.c -o 19_longest_common_increasing_subsequence

20_bubblesort: 20_bubblesort_main.c 20_bubblesort.c
	$(CXX) $(CXX_FLAGS) 20_bubblesort_main.c -o 20_bubblesort

21_insertionsort: 21_insertionsort_main.c 21_insertionsort.c
	$(CXX) $(CXX_FLAGS) 21_insertionsort_main.c -o 21_insertionsort

22_selectionsort: 22_selectionsort_main.c 22_selectionsort.c
	$(CXX) $(CXX_FLAGS) 22_selectionsort_main.c -o 22_selectionsort

23_mergesort: 23_mergesort_main.c 23_mergesort.c
	$(CXX) $(CXX_FLAGS) 23_mergesort_main.c -o 23_mergesort

24_quicksort: 24_quicksort_main.c 24_quicksort.c
	$(CXX) $(CXX_FLAGS) 24_quicksort_main.c -o 24_quicksort

25_heapsort: 25_heapsort_main.c 25_heapsort.c
	$(CXX) $(CXX_FLAGS) 25_heapsort_main.c -o 25_heapsort

26_quicksort: 26_quicksort_main.c 26_quicksort.c
	$(CXX) $(CXX_FLAGS) 26_quicksort_main.c -o 26_quicksort

30_euclid_GCD: 30_euclid_GCD_main.c 30_euclid_GCD.c
	$(CXX) $(CXX_FLAGS) 30_euclid_GCD_main.c -o 30_euclid_GCD

31_sieve_of_eratosthenes: 31_sieve_of_eratosthenes_main.c 31_sieve_of_eratosthenes.c
	$(CXX) $(CXX_FLAGS) 31_sieve_of_eratosthenes_main.c -o 31_sieve_of_eratosthenes

# note: 32_newtons_method has multiple functions inside
32_newtons_method: 32_newtons_method_main.c 32_newtons_method.c
	$(CXX) $(CXX_FLAGS) 32_newtons_method_main.c -o 32_newtons_method

50_check_sorted_or_reverse: 50_check_sorted_or_reverse_main.c 50_check_sorted_or_reverse.c
	$(CXX) $(CXX_FLAGS) 50_check_sorted_or_reverse_main.c -o 50_check_sorted_or_reverse

51_variance: 51_variance_main.c 51_variance.c
	$(CXX) $(CXX_FLAGS) 51_variance_main.c -o 51_variance

60_array_summary: 60_array_summary_main.c 60_array_summary.c
	$(CXX) $(CXX_FLAGS) 60_array_summary_main.c -o 60_array_summary

# Removes all object files and the executable (if they exist).
clean:
	rm -rf *.o 01_greatestof3 02_fib 03_sign 04_prime 05_parity 06_palindrome 10_find_val_in_array 11_array_max 12_check_sorted_array 13_check_arrays_equal 14_lexicographic_array_compare 15_check_heap_order 16_binary_search 17_edit_dist 18_longest_common_subsequence 19_longest_common_increasing_subsequence 20_bubblesort 21_insertionsort 22_selectionsort 23_mergesort 24_quicksort 25_heapsort 26_quicksort 30_euclid_GCD 31_sieve_of_eratosthenes 32_newtons_method 50_check_sorted_or_reverse 51_variance 60_array_summary