name: Lint and Test
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
jobs:
  lint-job:
    name: Linting Job
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
    - id: step1
      run: docker exec -w /app/code detached_repl make lint
  test-job:
    name: Unit Tests Job
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
    - id: step1
      run: docker exec -w /app/code detached_repl make tests
        
